<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="28APO2678" name="Ir A Recurso Interactivo Externo Alumno FireFox Test" tests="1" failures="1" timestamp="10 Aug 2016 06:25:15 GMT" time="46.009" errors="0">
  <testcase name="@AfterTest tearDown" time="0.0" classname="comPageObjectsTestSaviaDigital.IrARecursoInteractivoExternoAlumno">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at comPageObjectsTestSaviaDigital.IrARecursoInteractivoExternoAlumno.tearDown(IrARecursoInteractivoExternoAlumno.java:108)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase name="AbrirElemntoExternoAlumno" time="0.002" classname="comPageObjectsTestSaviaDigital.IrARecursoInteractivoExternoAlumno">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at comPageObjectsTestSaviaDigital.IrARecursoInteractivoExternoAlumno.AbrirElemntoExternoAlumno(IrARecursoInteractivoExternoAlumno.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- AbrirElemntoExternoAlumno -->
</testsuite> <!-- Ir A Recurso Interactivo Externo Alumno FireFox Test -->
